
node
{
   def mp = tool name: '/Users/vijaygovind/apache-maven-3.5.4', type: 'maven'
  
   stage('Preparation') { 
      // Get some code from a GitHub repository
      echo 'About to hit respository from github'
      git 'https://github.com/vijaycgovind/macExamples.git'
      
   }
     
  
}
